import type { Metadata } from "next";
import { Download } from "lucide-react";
import Header from "@/components/layout/Header";
import Footer from "@/components/layout/Footer";
import WhatsAppButton from "@/components/shared/WhatsAppButton";
import cjenik from "@/data/cjenik.json";

// Required by NN 101/2026 (Odluka o objavi cjenika + Odluka o isticanju dodatne cijene).
// Data comes from data/cjenik.json; the CSV files are generated by scripts/cjenik.mjs.

export const metadata: Metadata = {
  title: "Cjenik usluga",
  description:
    "Okvirni cjenik električarskih usluga Elektro Artis d.o.o., Zagreb. Cijene s PDV-om, uz cijenu na 10. 9. 2026.",
  alternates: {
    canonical: "https://elektro-artis.hr/cjenik",
  },
};

const ANCHOR_DATE = "2026-09-10";

const eur = (n: number) =>
  new Intl.NumberFormat("hr-HR", { style: "currency", currency: "EUR" }).format(n);

const hrDate = (iso: string) => {
  const [y, m, d] = iso.slice(0, 10).split("-");
  return `${Number(d)}. ${Number(m)}. ${y}.`;
};

const csvHref = (file: string) => `/cjenici/${encodeURIComponent(file)}`;

export default function CjenikPage() {
  const izdanja = [...cjenik.izdanja].reverse();
  const [trenutno, ...arhiva] = izdanja;

  return (
    <>
      <Header />
      <main>
        <section className="bg-blue pt-32 pb-12">
          <div className="max-w-5xl mx-auto px-4 sm:px-6 lg:px-8">
            <h1 className="font-[var(--font-dm-sans)] font-extrabold text-4xl sm:text-5xl text-white">
              Cjenik usluga
            </h1>
          </div>
        </section>

        <section className="py-16 bg-white">
          <div className="max-w-5xl mx-auto px-4 sm:px-6 lg:px-8">
            <p className="text-text text-lg mb-8">
              Svaki posao je individualan – točnu cijenu dajemo nakon upita ili pregleda.
              Okvirne cijene po elementima obračuna:
            </p>

            <div className="overflow-x-auto rounded-2xl border border-gray-100">
              <table className="w-full text-sm sm:text-base">
                <thead className="bg-blue-xlight text-left">
                  <tr>
                    <th scope="col" className="px-4 py-3 font-semibold text-text">Usluga</th>
                    <th scope="col" className="px-4 py-3 font-semibold text-text text-right whitespace-nowrap">
                      Cijena
                    </th>
                    <th scope="col" className="px-4 py-3 font-semibold text-muted text-right">
                      Cijena na 10. 9. 2026.
                    </th>
                  </tr>
                </thead>
                <tbody className="divide-y divide-gray-100">
                  {cjenik.stavke.map((s) => (
                    <tr key={s.naziv}>
                      <td className="px-4 py-3">
                        <span className="block text-text">{s.naziv}</span>
                        <span className="block text-xs text-muted mt-0.5">{s.obracun}</span>
                      </td>
                      <td className="px-4 py-3 text-right font-semibold text-text whitespace-nowrap">
                        {eur(s.cijena)}
                      </td>
                      <td className="px-4 py-3 text-right text-muted whitespace-nowrap">
                        {eur(s.sidrena_cijena)}
                        {s.sidrena_datum !== ANCHOR_DATE && (
                          <span className="block text-xs">na {hrDate(s.sidrena_datum)}</span>
                        )}
                      </td>
                    </tr>
                  ))}
                </tbody>
              </table>
            </div>

            <ul className="mt-6 space-y-1.5 text-sm text-muted list-disc pl-5">
              <li>Sve cijene su iskazane s uključenim PDV-om.</li>
              <li>Konačna cijena ovisi o udaljenosti i složenosti radova.</li>
              <li>Materijal se naplaćuje zasebno, po stavci.</li>
              <li>
                Uz svaku stavku istaknuta je i cijena na 10. 9. 2026., sukladno Odluci o
                isticanju dodatne cijene (NN 101/2026).
              </li>
            </ul>

            {trenutno && (
              <a
                href={csvHref(trenutno.datoteka)}
                download
                className="mt-8 inline-flex items-center gap-2 min-h-[44px] px-5 py-2.5 rounded-xl border border-blue/20 bg-blue-xlight hover:bg-blue-light text-blue font-semibold text-sm transition-colors active:scale-[0.97]"
              >
                <Download className="w-4 h-4" />
                Preuzmi cjenik (CSV)
              </a>
            )}

            <div className="mt-12">
              <h2 className="font-[var(--font-dm-sans)] font-bold text-lg text-text mb-3">
                Arhiva cjenika
              </h2>
              <ul className="space-y-1.5 text-sm">
                {izdanja.map((iz) => (
                  <li key={iz.datoteka}>
                    <a href={csvHref(iz.datoteka)} className="text-blue hover:underline break-all">
                      {iz.datoteka}
                    </a>
                    <span className="text-muted">
                      {" "}
                      · vrijedi od {hrDate(iz.vrijedi_od)}
                      {iz === trenutno && " (trenutačni)"}
                    </span>
                  </li>
                ))}
              </ul>
              {arhiva.length === 0 && (
                <p className="text-xs text-muted mt-2">Prethodnih izdanja još nema.</p>
              )}
            </div>
          </div>
        </section>
      </main>
      <Footer />
      <WhatsAppButton />
    </>
  );
}
